In [4]:
import pandas as pd

In [26]:
file_name = 'validation_agent_3.csv'

In [27]:
df = pd.read_csv('validation/'+file_name)

In [28]:
df.head(5)

,msg_cat_con,msg_cat_edu,msg_cat_ent,msg_cat_new,msg_cat_per,msg_com,msg_med,msg_qua,msg_que,msg_rel,msg_sal,msg_sen,like,comment,share,mood
0,0.0,1.0,0.0,0.0,0.0,0.108274,0.0,0.573336,1.0,0.491221,0.430644,0.103816,0,0,0,0.5
1,0.0,0.0,0.0,0.0,1.0,0.393745,1.0,0.744530,0.0,0.237846,0.181677,0.150197,0,0,0,0.5
2,0.0,0.0,0.0,0.0,1.0,0.856278,0.5,0.066495,0.0,0.321788,0.284852,0.627554,0,0,0,0.5
3,1.0,0.0,0.0,0.0,0.0,0.673731,1.0,0.586493,0.0,0.893329,0.828715,0.380374,0,0,0,0.5
4,1.0,0.0,0.0,0.0,0.0,0.914049,0.5,0.428219,1.0,0.338488,0.851313,0.271423,0,0,0,0.5

# Order columns

In [29]:
columnsTitles=["msg_cat_per","msg_cat_ent","msg_cat_new","msg_cat_edu","msg_cat_con","msg_rel","msg_qua","msg_sen","msg_sal","msg_med","msg_com","msg_que","like","comment","share","mood"]
df=df.reindex(columns=columnsTitles)

In [30]:
df.head(5)

,msg_cat_per,msg_cat_ent,msg_cat_new,msg_cat_edu,msg_cat_con,msg_rel,msg_qua,msg_sen,msg_sal,msg_med,msg_com,msg_que,like,comment,share,mood
0,0.0,0.0,0.0,1.0,0.0,0.491221,0.573336,0.103816,0.430644,0.0,0.108274,1.0,0,0,0,0.5
1,1.0,0.0,0.0,0.0,0.0,0.237846,0.744530,0.150197,0.181677,1.0,0.393745,0.0,0,0,0,0.5
2,1.0,0.0,0.0,0.0,0.0,0.321788,0.066495,0.627554,0.284852,0.5,0.856278,0.0,0,0,0,0.5
3,0.0,0.0,0.0,0.0,1.0,0.893329,0.586493,0.380374,0.828715,1.0,0.673731,0.0,0,0,0,0.5
4,0.0,0.0,0.0,0.0,1.0,0.338488,0.428219,0.271423,0.851313,0.5,0.914049,1.0,0,0,0,0.5

# Export to .csv

In [31]:
df.to_csv('validation/'+file_name, index=False)